### PR TITLE
my work time dialog implementatione

### PR DESCRIPTION
**Pull request by SSJGodGogeta**
Added dialog to add time entries into time table.

### CODE REVIEW

**Comment by SSJGodGogeta** [comment]
Dont merge yet. small changes to do.

**Comment by SSJGodGogeta** [comment]
ok, done. now u can look and approve+merge

**Comment by SSJGodGogeta** [comment]
right... dont merge. there are commits for my vacations on this now which isnt finished rn. will continue tmrw.

**Comment by SSJGodGogeta** [comment]
Alright; Vacations are done too. Now u can check and approve=>merge or deny. Some style changes need to be done (f.ex logout button, statistic positions, table design etc.)

**Review by Kevins35-de — APPROVED** [review]
i will let it through. But only this one time 🤨

**Pull request merged**
